sudo: false
cache: bundler
language: ruby
rvm:
  - 2.1.5
before_install:
  - gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rubocop
notifications:
  email: false
